package api

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/go-playground/validator/v10"
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger" // middlerware for echo-swagger
	db "github.com/tetrex/backend-masterclass-go/db/sqlc"
	_ "github.com/tetrex/backend-masterclass-go/docs" // docs is generated by Swag CLI
	"github.com/tetrex/backend-masterclass-go/util"
)

type Server struct {
	db        *db.Store
	router    *echo.Echo
	validator *validator.Validate
}

func NewServer(store *db.Store) *Server {
	router := echo.New()
	validator := util.NewValidator()

	server := &Server{
		db:        store,
		router:    router,
		validator: validator,
	}

	server.Start()
	return server
}

func (server *Server) Start() {

	// health check api
	server.router.GET("/", server.health)

	// swagger docs
	server.router.GET("/swagger/*", echoSwagger.WrapHandler)

	//v1 group
	v1 := server.router.Group("/v1")

	//account groups
	account := v1.Group("account")

	//accounts
	account.POST("/", server.createAccount)
	account.GET("/:id", server.getAccount)
	account.GET("/", server.listAccounts)

	// -------------
	s := &http.Server{
		Addr:    fmt.Sprintf(":%d", 8080),
		Handler: server.router,
	}

	log.Println("Starting server " + s.Addr)
	if err := s.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatal("Server startup failed")
	}
}

func (s *Server) health(c echo.Context) error {
	return c.JSON(http.StatusOK, util.OkResponse{Message: "server,all good", Data: time.Now().UnixNano()})
}
